name: Deploy to Servers

on:
  push:
    branches:
      - stage

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy to Server 2
        run: |
          ssh sretailbeautyunileve_admin@98.70.25.78 "cd /data/stage.retailbeauty.unilever.com/public_html && git pull origin stage"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_SERVER2 }}
