name: Deploy to Servers

on:
  push:
    branches:
      - stage

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        chmod 600 ~/.ssh/id_rsa
        echo "$SSH_PRIVATEKEY_SERVER2" > ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST_SERVER1 }} > ~/.ssh/known_hosts
        ssh-keyscan -H ${{ secrets.SSH_HOST_SERVER2 }} > ~/.ssh/known_hosts

    - name: Deploy to Server 1
      run: |
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST_SERVER2 }} "cd ${{ secrets.WORK_DIR }}  && git checkout ${{ secrets.STAGE_BRANCH }} && git pull origin stage && exit"
    
    - name: Deploy to Server 2
      run: |
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST_SERVER2 }} "cd ${{ secrets.WORK_DIR }}  && git checkout ${{ secrets.STAGE_BRANCH }} && git pull origin stage && exit"
