name: Deploy to Servers

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATEKEY_SERVER2 }}

      - name: Add Known Hosts
        run: |
          ssh-keyscan -H 98.70.39.120 >> ~/.ssh/known_hosts
          ssh-keyscan -H 98.70.25.78 >> ~/.ssh/known_hosts
          # Add more lines if you have additional servers

      - name: Deploy to Server 1
        run: |
          ssh -o StrictHostKeyChecking=yes root@98.70.39.120 "cd /data/stage.retailbeauty.unilever.com/public_html && git pull origin stage"

      - name: Deploy to Server 2
        run: |
          ssh -o StrictHostKeyChecking=yes root@98.70.25.78 "cd /data/stage.retailbeauty.unilever.com/public_html && git pull origin stage"
          # Add more lines if you have additional servers
